-- exec sp_who2;

USE [master];
ALTER DATABASE [EnterpriseHub] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
RESTORE DATABASE [EnterpriseHub] 
FROM DISK = N'F:\ia3pacific6\MSSQL\Backup\enterprisehub_post_mbi_frluna.bak' WITH FILE = 1, 
MOVE N'EnterpriseHub_Catalog' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Catalog.mdf', 
MOVE N'EnterpriseHub_Default' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Default.ndf', 
MOVE N'EnterpriseHub_Indexes1' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Indexes.ndf', 
MOVE N'EnterpriseHub_Indexes2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Indexes2.ndf', 
MOVE N'EnterpriseHub_Indexes3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Indexes3.ndf', 
MOVE N'EnterpriseHub_Indexes4' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Indexes4.ndf', 
MOVE N'EnterpriseHub_Member' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member.ndf', 
MOVE N'EnterpriseHub_Member2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member2.ndf', 
MOVE N'EnterpriseHub_Member3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member3.ndf', 
MOVE N'EnterpriseHub_Member4' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member4.ndf', 
MOVE N'EnterpriseHub_Member5' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member5.ndf', 
MOVE N'EnterpriseHub_Member6' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member6.ndf', 
MOVE N'EnterpriseHub_Member7' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member7.ndf', 
MOVE N'EnterpriseHub_Member8' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Member8.ndf', 
MOVE N'EnterpriseHub_Provider' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider.ndf', 
MOVE N'EnterpriseHub_Provider2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider2.ndf', 
MOVE N'EnterpriseHub_Provider3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider3.ndf', 
MOVE N'EnterpriseHub_Provider4' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider4.ndf', 
MOVE N'EnterpriseHub_Provider5' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider5.ndf', 
MOVE N'EnterpriseHub_Provider6' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider6.ndf', 
MOVE N'EnterpriseHub_Provider7' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider7.ndf', 
MOVE N'EnterpriseHub_Provider8' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Provider8.ndf', 
MOVE N'EnterpriseHub_Reference' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Reference.ndf', 
MOVE N'EnterpriseHub_Reference2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Reference2.ndf', 
MOVE N'EnterpriseHub_Reference3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Reference3.ndf', 
MOVE N'EnterpriseHub_Reference4' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Reference4.ndf', 
MOVE N'EnterpriseHub_Financial1' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Financial1.ndf', 
MOVE N'EnterpriseHub_Financial2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_Financial2.ndf', 
MOVE N'EnterpriseHub_GeneralClaims1' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims1.ndf', 
MOVE N'EnterpriseHub_GeneralClaims2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims2.ndf', 
MOVE N'EnterpriseHub_GeneralClaims3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims3.ndf', 
MOVE N'EnterpriseHub_GeneralClaims4' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims4.ndf', 
MOVE N'EnterpriseHub_GeneralClaims5' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims5.ndf', 
MOVE N'EnterpriseHub_GeneralClaims6' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims6.ndf', 
MOVE N'EnterpriseHub_GeneralClaims7' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims7.ndf', 
MOVE N'EnterpriseHub_GeneralClaims8' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_GeneralClaims8.ndf', 
MOVE N'EnterpriseHub_PharmacyClaims1' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_PharmacyClaims1.ndf', 
MOVE N'EnterpriseHub_PharmacyClaims2' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_PharmacyClaims2.ndf', 
MOVE N'EnterpriseHub_PharmacyClaims3' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_PharmacyClaims3.ndf', 
MOVE N'Authorizations' TO N'F:\ia3pacific6\MSSQL\DATA\Authorizations.ndf', 
MOVE N'EnterpriseHub_ClinicalProfile' TO N'F:\ia3pacific6\MSSQL\DATA\EnterpriseHub_ClinicalProfile.ndf', 
NOUNLOAD, REPLACE, STATS = 5;
ALTER DATABASE [EnterpriseHub] SET MULTI_USER;
GO