--NAME_PROVIDER
--NAME
--STG_HCFA_NAME_ORG
--STG_HCFA_DATE

USE ADWODSSTG;
--=============================
--NAME
--STG_HCFA_NAME_ORG
--=============================
SELECT
A.NAME_ID
,A.NAME_PRE
,A.NAME_FIRST
,A.NAME_MI
,A.NAME_LAST
,A.NAME_SUF
,A.ENTER_DATE
,A.ENTER_BY
,A.GENDER
,A.BIRTH_DATE
,A.UPDATE_DATE
,A.UPDATE_STAFF
,A.SOURCE_SYSTEM
,A.PROGRAM_ID
,B.LANGUAGE
,B.RACE
,B.DEATH_DATE
,B.ORIGIN_DATE
,C.CompanyMRefId
,D.MemberRecId
FROM STG_NAME A
INNER JOIN STG_HCFA_NAME_ORG B ON A.NAME_ID = B.NAME_ID 
						  AND A.SOURCE_SYSTEM = B.SOURCE_SYSTEM
LEFT JOIN (SELECT NAME_ID, SOURCE_SYSTEM, MAX(UPDATE_DATE) AS UPDATE_DATE
		 FROM STG_NAME_SCRIPT
		 GROUP BY NAME_ID, SOURCE_SYSTEM) NS ON NS.NAME_ID = A.NAME_ID AND NS.SOURCE_SYSTEM = A.SOURCE_SYSTEM
INNER JOIN ENTERPRISEHUB.MRef.Company C ON A.SOURCE_SYSTEM = C.DISPLAYCODE
INNER JOIN ENTERPRISEHUB.XRef.Member D ON C.COMPANYMREFID = D.COMPANYMREFID 
								AND A.NAME_ID = D.EXTERNALVALUE
WHERE 1=1
AND (A.PROGRAM_ID LIKE 'M%'
    OR A.PROGRAM_ID = 'XXX' OR A.PROGRAM_ID = 'XXD')
AND D.ExternalTypeMRefId = 1
AND (
	   (B.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), B.LAST_UPDT_DATE, 112)  > '20160705') OR 
         (B.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), B.LAST_UPDT_DATE, 112)  >  '20160705') OR
	   (A.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), A.UPDATE_DATE, 112)  > '20160705') OR 
         (A.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), A.UPDATE_DATE, 112)  >  '20160705') OR
	   (NS.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), NS.UPDATE_DATE, 112)  > '20160705') OR 
         (NS.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), NS.UPDATE_DATE, 112)  >  '20160705')

    )
	AND A.NAME_ID = 'N00318220606'
UNION
SELECT
A.NAME_ID
,A.NAME_PRE
,A.NAME_FIRST
,A.NAME_MI
,A.NAME_LAST
,A.NAME_SUF
,A.ENTER_DATE
,A.ENTER_BY
,A.GENDER
,A.BIRTH_DATE
,A.UPDATE_DATE
,A.UPDATE_STAFF
,A.SOURCE_SYSTEM
,A.PROGRAM_ID
,B.LANGUAGE
,B.RACE
,B.DEATH_DATE
,B.ORIGIN_DATE
,C.CompanyMRefId
,D.MemberRecId
FROM STG_NAME A
INNER JOIN STG_HCFA_NAME_ORG B ON A.NAME_ID = B.NAME_ID 
						  AND A.SOURCE_SYSTEM = B.SOURCE_SYSTEM 
LEFT JOIN (SELECT NAME_ID, SOURCE_SYSTEM, MAX(UPDATE_DATE) AS UPDATE_DATE
		 FROM STG_NAME_SCRIPT
		 GROUP BY NAME_ID, SOURCE_SYSTEM) NS ON NS.NAME_ID = A.NAME_ID AND NS.SOURCE_SYSTEM = A.SOURCE_SYSTEM
INNER JOIN ENTERPRISEHUB.MRef.Company C ON A.SOURCE_SYSTEM = C.DISPLAYCODE
INNER JOIN ENTERPRISEHUB.XRef.Member D ON C.COMPANYMREFID = D.COMPANYMREFID 
								  AND A.NAME_ID = D.EXTERNALVALUE
WHERE (A.PROGRAM_ID LIKE 'M%'
OR A.PROGRAM_ID = 'XXX' OR A.PROGRAM_ID = 'XXD')
AND D.ExternalTypeMRefId = 1
AND (
	   (B.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), B.LAST_UPDT_DATE, 112)  > '20160705') OR 
         (B.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), B.LAST_UPDT_DATE, 112)  >  '20160705') OR
	   (A.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), A.UPDATE_DATE, 112)  > '20160705') OR 
         (A.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), A.UPDATE_DATE, 112)  >  '20160705') OR
	   (NS.SOURCE_SYSTEM= 'MMM' AND CONVERT(nvarchar(8), NS.UPDATE_DATE, 112)  >  '20160705') OR 
         (NS.SOURCE_SYSTEM= 'PMC' AND CONVERT(nvarchar(8), NS.UPDATE_DATE, 112)  >  '20160705')
    )
	AND A.NAME_ID = 'N00318220606'
;


--=============================
--STG_HCFA_DATE
--=============================
SELECT 
DATE_ID
,NAME_ID
,INDICATOR
,PREFERRED
,UPDATE_STAFF
,CREATE_STAFF
,VALUE
,SOURCE_SYSTEM
,START_DATE
,END_DATE
,UPDATE_DATE
,CREATE_DATE
FROM STG_HCFA_DATE
WHERE NAME_ID = 'N00318220606'
;

--=============================
--NAME_PROVIDER
--=============================
SELECT 
A.NAME_ID as MP_mNameID
,A.PROVIDER_ID as MP_pNameID
,A.CREATE_STAFF
,A.UPDATE_STAFF
,cast(A.TERM_REASON as varchar(50))TERM_REASON
,cast(A.SOURCE_SYSTEM as varchar(3))SOURCE_SYSTEM
,isnull(cast(A.SERVICE_TYPE as varchar(50)),0) AS SERVICE_TYPE
,A.EFF_DATE
,A.TERM_DATE
,A.CREATE_DATE
,A.UPDATE_DATE
,cast(Replace(B.SOC_SEC,'-','')  as varchar(9)) as MP_pSSN
,UPPER(LEFT(LTRIM(RTRIM(isnull(cast(B.COMPANY as varchar(50)),0))),10))  AS MP_NPI
,C.CompanyMRefId
,ltrim(rtrim(B.Program_ID)) as MP_pStatus
,UPPER(RIGHT(LTRIM(RTRIM(isnull(cast(B.COMPANY as varchar(50)),0))),10))  AS MP_BILL_NPI
FROM STG_NAME_PROVIDER A
INNER JOIN STG_NAME B
ON A.PROVIDER_ID = B.NAME_ID
AND A.SOURCE_SYSTEM = B.SOURCE_SYSTEM
INNER JOIN ENTERPRISEHUB.[MRef].[Company] C
ON A.SOURCE_SYSTEM = C.DisplayCode
WHERE A.SERVICE_TYPE = 'PCP'
	AND NAME_ID = 'N00318220606'
ORDER BY
A.NAME_ID
,A.SOURCE_SYSTEM
;




SELECT *
FROM  [ADWODSSTG].[dbo].[STG_ADW_MemberIndicator] with(NOLOCK)
WHERE MemberRecId = 92933
	AND CONVERT(VARCHAR,ModificationDate,112) = '20170111'
;


SELECT MI.*
FROM  [EnterpriseHub].dbo.MemberCompany MC
	INNER JOIN [EnterpriseHub].dbo.MemberIndicator MI
	ON MC.CompanyMRefId = MI.CompanyMRefId AND MC.MemberRecId = MI.MemberRecId
WHERE MI.MemberRecId = 92933
--	AND MI.IndMRefId IN(24,11)
	AND IndValue = 'P00342418603'
;



